name: GitHub Actions
run-name: Functions update
on: [push]
  # schedule:
  #   - cron: '*/4 * * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
      - run: npm --v