name: Auto Updater
run-name: Functions update
on: [push]
  # schedule:
  #   - cron: '*/4 * * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: subdir/package-lock.json
      - run: npm --v