name: Auto Updater
run-name: Functions update
on: [push] 
  # schedule:
  #   - cron: '*/4 * * * *'
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm start
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 